# Nacos\u670D\u52A1\u6CE8\u518C
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
        client-ip: localhost
  application:
    name: mall-auth
  # \u7EDF\u4E00\u7684\u5168\u5C40\u7684--\u8BBE\u7F6E\u670D\u52A1\u5668\u54CD\u5E94\u7ED9\u5BA2\u6237\u7AEF\u7684\u65E5\u671F\u65F6\u95F4\u683C\u5F0F
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false # \u5173\u95EDThymeleaf\u7684\u7F13\u5B58
  redis:
    host: 192.168.56.100
    port: 6379
  session:
    store-type: redis
    redis:
      namespace: spring:session
server:
  port: 30000
  servlet:
    session:
      timeout: 30m # session 超时30分钟
management:
  endpoints:
    web:
      exposure:
        include: '*'
